export default [
  {
    login: "aimeirak",
    id: 15193422,
    node_id: "MDQ6VXNlcjE1MTkzNDIy",
    avatar_url: "https://avatars.githubusercontent.com/u/15193422?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aimeirak",
    html_url: "https://github.com/aimeirak",
    followers_url: "https://api.github.com/users/aimeirak/followers",
    following_url: "https://api.github.com/users/aimeirak/following{/other_user}",
    gists_url: "https://api.github.com/users/aimeirak/gists{/gist_id}",
    starred_url: "https://api.github.com/users/aimeirak/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aimeirak/subscriptions",
    organizations_url: "https://api.github.com/users/aimeirak/orgs",
    repos_url: "https://api.github.com/users/aimeirak/repos",
    events_url: "https://api.github.com/users/aimeirak/events{/privacy}",
    received_events_url: "https://api.github.com/users/aimeirak/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "jajajaden01",
    id: 37714031,
    node_id: "MDQ6VXNlcjM3NzE0MDMx",
    avatar_url: "https://avatars.githubusercontent.com/u/37714031?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jajajaden01",
    html_url: "https://github.com/jajajaden01",
    followers_url: "https://api.github.com/users/jajajaden01/followers",
    following_url: "https://api.github.com/users/jajajaden01/following{/other_user}",
    gists_url: "https://api.github.com/users/jajajaden01/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jajajaden01/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jajajaden01/subscriptions",
    organizations_url: "https://api.github.com/users/jajajaden01/orgs",
    repos_url: "https://api.github.com/users/jajajaden01/repos",
    events_url: "https://api.github.com/users/jajajaden01/events{/privacy}",
    received_events_url: "https://api.github.com/users/jajajaden01/received_events",
    type: "User",
    site_admin: false
  },
];
