export default {  	
  login:	"NDAYISENGAManu",
  id:	47325072,
  node_id:	"MDQ6VXNlcjQ3MzI1MDcy",
  avatar_url:	"https://avatars.githubusercontent.com/u/47325072?v=4",
  gravatar_id:	"",
  url:	"https://api.github.com/users/NDAYISENGAManu",
  html_url:	"https://github.com/NDAYISENGAManu",
  followers_url:	"https://api.github.com/users/NDAYISENGAManu/followers",
  following_url:	"https://api.github.com/users/NDAYISENGAManu/following{/other_user}",
  gists_url:	"https://api.github.com/users/NDAYISENGAManu/gists{/gist_id}",
  starred_url:	"https://api.github.com/users/NDAYISENGAManu/starred{/owner}{/repo}",
  subscriptions_url:	"https://api.github.com/users/NDAYISENGAManu/subscriptions",
  organizations_url:	"https://api.github.com/users/NDAYISENGAManu/orgs",
  repos_url:	"https://api.github.com/users/NDAYISENGAManu/repos",
  events_url:	"https://api.github.com/users/NDAYISENGAManu/events{/privacy}",
  received_events_url:	"https://api.github.com/users/NDAYISENGAManu/received_events",
  type:	"User",
  site_admin:	false,
  name:	"NDAYISENGA Emmanuel ",
  company:	"BK Techouse Ltd",
  blog:	"",
  location:	"kigali city",
  email:	null,
  hireable:	null,
  bio:	"Software Developer - #Front-end Engineer - #UI/UX - #React/Angular - #Figma - #Root user - #Linux - #Sass - #Js - </>",
  twitter_username:	"SengaManu",
  public_repos:	6,
  public_gists:	0,
  followers:	2,
  following:	3,
  created_at:	"2019-02-04T14:16:03Z",
  updated_at:	"2022-08-23T11:52:32Z",
};
